name: progressify_core
description: Core Reusables for Progressify
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.4.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  form_field_validator: ^1.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  simple_moment: ^1.1.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
