name: progressify_core
description: Core Reusables for Progressify
version: 0.0.8
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: 3.5.1
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.5.0
  form_field_validator: 1.1.0
  get_it: 7.6.0
  http: 0.13.6
  simple_moment: 1.1.1
  url_launcher: 6.1.12
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

flutter:
