name: progressify_core
description: Core Reusables for Progressify
version: 0.0.9
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.4
  font_awesome_flutter: ^10.5.0
  form_field_validator: ^1.1.0
  get_it: ^7.6.0
  http: ^1.1.0
  simple_moment: ^1.1.1
  url_launcher: ^6.1.12
dependency_overrides:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
